// Temporarily comment out entire file
/*
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBupTZY-LkAgX6SErx4gMyrIB3PN-zJRL8',
    appId: '1:431193209939:web:2289fc7d377c857f01daa6',
    messagingSenderId: '431193209939',
    projectId: 'grantly-d425b',
    authDomain: 'grantly-d425b.firebaseapp.com',
    storageBucket: 'grantly-d425b.firebasestorage.app',
    measurementId: 'G-CWNWD2S10Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCe6yLmi0VkMaw1_CSYDi0yhZVwEh8158g',
    appId: '1:431193209939:android:be474af99d3b2e3801daa6',
    messagingSenderId: '431193209939',
    projectId: 'grantly-d425b',
    storageBucket: 'grantly-d425b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8qgA32VSzcfjx93ulqTLCnezfjQduLcA',
    appId: '1:431193209939:ios:2d5cbf326e6b966a01daa6',
    messagingSenderId: '431193209939',
    projectId: 'grantly-d425b',
    storageBucket: 'grantly-d425b.firebasestorage.app',
    iosBundleId: 'com.ephriamlabs.grantly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8qgA32VSzcfjx93ulqTLCnezfjQduLcA',
    appId: '1:431193209939:ios:0cb00770302b4f9901daa6',
    messagingSenderId: '431193209939',
    projectId: 'grantly-d425b',
    storageBucket: 'grantly-d425b.firebasestorage.app',
    iosBundleId: 'com.example.scholarshipMatchMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBupTZY-LkAgX6SErx4gMyrIB3PN-zJRL8',
    appId: '1:431193209939:web:438b0689c54ae2be01daa6',
    messagingSenderId: '431193209939',
    projectId: 'grantly-d425b',
    authDomain: 'grantly-d425b.firebaseapp.com',
    storageBucket: 'grantly-d425b.firebasestorage.app',
    measurementId: 'G-3CK9TETD0Q',
  );
}
*/
