# Generated by Django 4.2.10 on 2025-02-28 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ScholarshipTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("slug", models.SlugField(blank=True, max_length=255, unique=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Scholarship Tag",
                "verbose_name_plural": "Scholarship Tags",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Scholarship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("deadline", models.DateField()),
                ("eligibility_criteria", models.TextField()),
                ("is_active", models.BooleanField(default=True)),
                ("education_level", models.CharField(blank=True, max_length=50)),
                ("field_of_study", models.CharField(blank=True, max_length=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tags",
                    models.ManyToManyField(
                        related_name="scholarships", to="scholarships.scholarshiptag"
                    ),
                ),
            ],
            options={
                "verbose_name": "Scholarship",
                "verbose_name_plural": "Scholarships",
                "ordering": ["-created_at"],
            },
        ),
    ]
