# Generated by Django 4.2.10 on 2025-02-02 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scholarships", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="scholarship",
            name="education_level",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="scholarship",
            name="field_of_study",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="scholarship",
            name="eligibility_criteria",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="scholarship",
            name="tags",
            field=models.ManyToManyField(
                related_name="scholarships", to="scholarships.scholarshiptag"
            ),
        ),
        migrations.AlterField(
            model_name="scholarship",
            name="title",
            field=models.CharField(max_length=200),
        ),
    ]
