coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 1%
    patch:
      default:
        target: 80%
        threshold: 1%

flags:
  auth:
    paths:
      - apps/users/tests/test_auth.py
      - apps/users/tests/test_tokens.py
      - apps/users/tests/test_token_expiration.py
  profile:
    paths:
      - apps/users/tests/test_profile.py
  social:
    paths:
      - apps/users/tests/test_social_auth.py
  integration:
    paths:
      - apps/users/tests/test_integration.py
  scholarships:
    paths:
      - apps/scholarships/tests/test_scholarship_models.py
      - apps/scholarships/tests/test_scholarship_views.py
      - apps/scholarships/tests/test_scholarship_serializers.py
  applications:
    paths:
      - apps/applications/tests/test_application_models.py
      - apps/applications/tests/test_application_views.py
      - apps/applications/tests/test_application_serializers.py

comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false 