# Generated by Django 4.2.10 on 2025-03-01 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_userprofile_education_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="credits",
            field=models.IntegerField(default=3),
        ),
    ]
