# Generated by Django 4.2.10 on 2025-03-01 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_userprofile_credits"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "user", "verbose_name_plural": "users"},
        ),
        migrations.RemoveField(
            model_name="user",
            name="apple_id",
        ),
        migrations.RemoveField(
            model_name="user",
            name="google_id",
        ),
        migrations.RemoveField(
            model_name="user",
            name="phone_verification_code",
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number",
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterModelTable(
            name="user",
            table=None,
        ),
    ]
