# Generated by Django 4.2.10 on 2025-03-04 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_user_phone_number"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
        migrations.AddField(
            model_name="user",
            name="firebase_uid",
            field=models.CharField(max_length=128, null=True, unique=True),
        ),
        migrations.AlterModelTable(
            name="user",
            table="users",
        ),
    ]
