# Generated by Django 4.2.10 on 2025-03-05 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_userprofile_hear_about_us_userprofile_location_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(
                fields=["firebase_uid"], name="user_profil_firebas_c3f353_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(fields=["email"], name="user_profil_email_8a1024_idx"),
        ),
    ]
