# Generated by Django 4.2.10 on 2025-03-05 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_userprofile_user_profil_firebas_c3f353_idx_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(
                fields=["created_at"], name="user_profil_created_26443b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(fields=["user"], name="user_profil_user_id_fbe33d_idx"),
        ),
    ]
