# Generated by Django 5.1.5 on 2025-01-31 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="apple_id",
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="google_id",
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
