# Generated by Django 5.1.5 on 2025-01-29 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="user",
            name="date_of_birth",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                choices=[("student", "Student"), ("admin", "Admin")],
                default="student",
                max_length=20,
            ),
        ),
        migrations.AlterModelTable(
            name="user",
            table="users",
        ),
    ]
