# Generated by Django 5.1.5 on 2025-01-29 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_bio_user_date_of_birth_user_user_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="bio",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
