# Generated by Django 5.1.5 on 2025-01-30 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_user_bio"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="user",
            table=None,
        ),
    ]
