# Generated by Django 5.1.5 on 2025-01-29 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("scholarships", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="scholarship",
            name="eligibility_criteria",
            field=models.TextField(default="No criteria specified"),
        ),
        migrations.AddField(
            model_name="scholarship",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="scholarship",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
