name: Django Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_DB: github_actions
          POSTGRES_USER: github_actions
          POSTGRES_PASSWORD: github_actions
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
        
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create .env file
      run: |
        echo "DJANGO_SECRET_KEY='django-insecure-test-key-for-github-actions'" > .env
        echo "DJANGO_DEBUG=True" >> .env
        echo "DB_NAME=github_actions" >> .env
        echo "DB_USER=github_actions" >> .env
        echo "DB_PASSWORD=github_actions" >> .env
        echo "DB_HOST=localhost" >> .env
        echo "DB_PORT=5432" >> .env
        
    - name: Run Tests
      env:
        DJANGO_SETTINGS_MODULE: backend.settings
      run: |
        python manage.py test

    - name: Run Migrations
      run: |
        python manage.py makemigrations
        python manage.py migrate